lsi: false
safe: true
source: ['http://maxime-barry-sqli.github.io/']
incremental: false
highlighter: rouge
include: [".well-known"]
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge